"""Add avatar column to User

Revision ID: 226dc2d8977f
Revises: e8cf11d55165
Create Date: 2025-10-21 11:51:11.184499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226dc2d8977f'
down_revision = 'e8cf11d55165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
