"""Add multi-stage shipping tracking to Order

Revision ID: e8cf11d55165
Revises: a8aae2eb6812
Create Date: 2025-10-20 14:09:53.227835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cf11d55165'
down_revision = 'a8aae2eb6812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_stage_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('in_transit_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivered_date')
        batch_op.drop_column('in_transit_date')
        batch_op.drop_column('shipped_date')
        batch_op.drop_column('processing_date')
        batch_op.drop_column('shipping_stage_index')

    # ### end Alembic commands ###
